const AccountInfoStyles = {
  modalProfileContainer: {
    flex: 1,
  },
  modalProfileHeader: {
    width: '100%',
    height: null,
    backgroundColor: '#1F5D44',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
  },
  modalProfileCloseButton: {
    borderRadius: 99,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
    height: 40,
  },
  modalProfileGeneralText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 13,
    color: '#555',
    alignSelf: 'center',
    marginVertical: 20,
  },
  modalProfileInput: {
    flexDirection: 'column',
    paddingHorizontal: 10,
  },
  modalProfileInputTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 15,
    color: '#555',
    marginBottom: 5,
    marginTop: 10,
  },
  modalProfileInputArea: {
    height: 50,
    width: '100%',
    borderWidth: 0.8,
    borderColor: '#888',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    paddingHorizontal: 5,
    borderRadius: 8,
  },
  modalProfileSaveButton: {
    width: '95%',
    height: 45,
    backgroundColor: '#14B219',
    alignSelf: 'center',
    borderRadius: 30,
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalProfileSaveButtonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#fff',
  },
  modalProfileGenderArea: {
    height: 50,
    width: '48%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    paddingHorizontal: 5,
    borderRadius: 8,
    flexDirection: 'row',
  },
  modalProfileGenderText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    color: '#555',
    marginLeft: 10,
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#fff',
  },
};

const OwnerInfoStyles = {
  ownerModalWpTitleArea: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'space-evenly',
    marginTop: 20,
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#fff',
  },
  ownerModalWpTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 15,
    color: '#1F5D44',
  },
  ownerModalWpText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    width: 300,
  },
  ownerModaInputTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#222',
    textAlign: 'center',
    alignSelf: 'center',
  },
  modalProfileContainer: {
    flex: 1,
  },
  modalProfileHeader: {
    width: '100%',
    height: null,
    backgroundColor: '#1F5D44',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    paddingHorizontal: 10,
  },
  modalProfileCloseButton: {
    borderRadius: 99,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
    height: 40,
  },
  modalProfileGeneralText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 13,
    color: '#555',
    alignSelf: 'center',
    marginVertical: 20,
  },
  modalProfileInput: {
    flexDirection: 'column',
    paddingHorizontal: 10,
  },
  modalProfileInputTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 15,
    color: '#555',
    marginBottom: 5,
    marginTop: 10,
  },
  modalProfileSaveButton: {
    width: '95%',
    height: 45,
    backgroundColor: '#14B219',
    alignSelf: 'center',
    borderRadius: 30,
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalProfileSaveButtonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#fff',
  },
  modalProfileGenderArea: {
    height: 50,
    width: '48%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    paddingHorizontal: 5,
    borderRadius: 8,
    flexDirection: 'row',
  },
  modalProfileGenderText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    color: '#555',
    marginLeft: 10,
  },
  timeText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 15,
    color: '#000',
  },
};

const HomeStyle = {
  container: {
    flex: 1,
  },
  header: {
    padding: 10,
    flex: 0.2,
    flexDirection: 'column',
    backgroundColor: '#1F5D44',
    paddingTop: 0,
  },
  body: {
    flex: 1,
    padding: 10,
  },
  categories: {
    height: 120,
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginBottom: 20,
  },
  categorieTab: {
    width: 70,
    height: 70,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  categorieTitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    color: '#888',
  },
  card: {
    height: 160,
    width: '100%',
    backgroundColor: '#FCD15C',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  card_title: {
    fontFamily: 'Manrope-Bold',
    color: '#333',
    fontSize: 16,
  },
  card_text: {
    fontFamily: 'Manrope-Regular',
    color: '#333',
    fontSize: 14,
    marginTop: 15,
  },
  card_button: {
    backgroundColor: '#fff',
    width: '60%',
    height: 45,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  card_button_text: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#FCD15C',
  },
  recentSearch: {
    height: 200,
    width: '100%',
  },
  recentSearchCard: {
    flexDirection: 'column',
    width: 130,
    height: 150,
    marginRight: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,

    elevation: 5,
    paddingLeft: 5,
  },
  recentSearchBottom: {
    backgroundColor: '#fff',
    flex: 0.3,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  add: {
    height: 160,
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 5,
    marginBottom: 40,
    marginTop: 0,
  },
  searchPopular: {
    backgroundColor: '#fff',
    borderRadius: 5,
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 10,
  },
  popularTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#333',
    marginTop: 10,
  },
  popularButton: {
    width: '100%',
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
  },
  popularText: {
    fontFamily: 'Manrope-Regular',
    color: '#1F5D44',
    width: 100,
  },
  header_top: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  header_bottom: {
    flex: 1,
    alignItems: 'center',
  },
  title: {
    fontFamily: 'Manrope-Bold',
    color: '#fff',
    fontSize: 20,
  },
  header_button: {
    backgroundColor: '#fff',
    width: '100%',
    height: 40,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
  },
  header_button_text: {
    color: '#333',
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    marginLeft: 10,
  },
  modalRecentText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#3C4048',
    marginHorizontal: 10,
  },
  modalScrollView: {
    height: 200,
    backgroundColor: 'red',
    marginBottom: 10,
    marginTop: 5,
  },
  modalHeader: {
    width: '100%',
    height: 50,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2.22,

    elevation: 3,
  },
  modalCloseButton: {
    borderRadius: 99,
    marginLeft: 10,
  },
  modalHeaderTitle: {
    marginLeft: 20,
    fontFamily: 'Manrope-Regular',
    fontSize: 18,
    color: '#888',
  },
  modalCategoriesCardArea: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  modalCategoriesCard: {
    width: 60,
    height: 60,
    backgroundColor: '#fff',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  modalCategories: {
    height: 80,
    marginVertical: 10,
    flexDirection: 'row',
  },
  modalPrivateText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 13,
    color: '#3C4048',
    marginLeft: 10,
  },
  modalTop: {
    backgroundColor: '#fff',
  },
};

const MyAddsStyles = {
  container: {
    flex: 1,
  },
  itemStyle: {
    fontSize: 20,
    padding: 10,
  },
  header: {
    flex: 0.1,
    backgroundColor: '#1F5D44',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    color: '#fff',
    fontSize: 20,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabStyle: {
    borderWidth: 0,
    borderColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    backgroundColor: '#eee',
    width: '100%',
  },
  activeTabStyle: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#14B219',
  },
  tabTextStyle: {
    color: '#666',
    padding: 5,
  },
  activeTabTextStyle: {
    color: '#14B219',
  },
  optionModalClose: {
    width: 40,
    height: 40,
    borderRadius: 99,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    position: 'absolute',
    right: 10,
    top: -10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  optionModalText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#14B219',
  },
  optionModalTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 16,
    color: '#555',
    marginBottom: 10,
    marginRight: 50,
  },
  optionModalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 45,
    width: '100%',
    paddingHorizontal: 10,
  },
  favoriteCardOptions: {
    position: 'absolute',
    bottom: 10,
    right: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 99,
  },
  favoriteCardTimeInfo: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    color: '#888',
    marginTop: 5,
  },
  favoriteCardInfoRow: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 15,
    color: '#888',
  },
  favoriteCardTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#666',
    marginTop: 5,
  },
  favoriteCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 80,
  },
  favoriteCardInfoArea: {
    width: 240,
    height: '100%',
    marginRight: 10,
    justifyContent: 'center',
  },
  imgArea: {
    height: 100,
    width: 100,
    backgroundColor: '#ddd',
    marginLeft: 10,
    borderRadius: 8,
    marginRight: 10,
  },
  controlButton: {
    height: 40,
    backgroundColor: '#14B219',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginTop: 5,
    borderRadius: 5,
  },
  controlButtonText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 16,
    color: '#fff',
  },
};

const DetailStyle = {
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  largeImg: {
    width: null,
    height: null,
    flex: 1,
    resizeMode: 'contain',
  },
  infoTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#000',
  },
  petInfo: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    color: '#666',
  },
  adDate: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    color: '#999',
    marginLeft: 5,
  },
  heartButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 99,
    position: 'absolute',
    top: 370,
    left: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  callButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 99,
    position: 'absolute',
    top: 370,
    right: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  messageButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 99,
    position: 'absolute',
    top: 370,
    right: 70,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  emptyButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 99,
    position: 'absolute',
    top: 370,
    right: 120,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  categoryTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#000',
  },
  fieldTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 13,
    color: '#000',
  },
  greyLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#ddd',
    marginTop: 5,
  },
  avatar: {
    width: 45,
    height: 45,
    backgroundColor: 'red',
    borderRadius: 99,
    position: 'absolute',
    top: -22.5,
    left: 'auto',
  },
  avatarName: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#000',
    marginTop: 30,
  },
  filledButton: {
    height: 40,
    width: '42%',
    backgroundColor: '#14B219',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  outlineButton: {
    height: 40,
    width: '90%',
    borderWidth: 1,
    borderColor: '#14B219',
    borderRadius: 30,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dotStyle: {
    position: 'absolute',
    zIndex: 1,
    right: 20,
    width: 40,
    height: 40,
    top: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chevronBack: {
    position: 'absolute',
    zIndex: 1,
    left: 30,
    width: 40,
    height: 40,
    top: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowCenter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fieldArea: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  iconArea: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
    color: '#fff',
  },
  fieldText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
    color: '#666',
  },
  tabStyle: {
    borderWidth: 0,
    borderColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  activeTabStyle: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#14B219',
  },
  tabTextStyle: {
    color: '#666',
  },
  activeTabTextStyle: {
    color: '#14B219',
  },
  explanation: {
    padding: 20,
  },
  explanationPhragraph: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#666',
    lineHeight: 25,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  modalTitle: {
    width: '100%',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBody: {
    width: '100%',
    height: 150,
  },
  modalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: 55,
  },
  closeModal: {
    width: 40,
    height: 40,
    borderRadius: 99,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    right: 10,
    top: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,

    elevation: 6,
    zIndex: 1,
  },
};

const BreedsStyle = {
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
  },
  container: {},
  largeImg: {
    width: null,
    height: null,
    flex: 1,
    resizeMode: 'contain',
  },
  tabStyle: {
    borderWidth: 0,
    borderRadius: 0,
    borderColor: 'transparent',
    borderBottomWidth: 0,
    borderBottomColor: '#ddd',
    backgroundColor: 'transparent',
  },
  activeTabStyle: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#fff',
  },
  tabTextStyle: {
    color: '#fff',
    fontFamily: 'Manrope-Bold',
  },
  topCollectionCard: {
    flexDirection: 'column',
    width: 230,
    height: 150,
    margin: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,

    elevation: 5,
  },
  topCollectionCardBottom: {
    backgroundColor: '#fff',
    flex: 0.3,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  activeTabTextStyle: {
    color: '#fff',
  },
  topCollections: {
    width: '100%',
  },
  featuredImage: {
    width: null,
    height: null,
    flex: 1,
    resizeMode: 'contain',
    margin: 10,
    borderRadius: 12,
  },
  title: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 18,
    color: '#1F5D44',
    marginLeft: 10,
    marginTop: 5,
  },
  popularBreeds: {
    height: 200,
    marginBottom: 0,
    width: '100%',
    marginTop: 10,
    margin: 10,
  },
  featuredTitle: {
    fontFamily: 'Manrope-Regular',
    color: '#fff',
    fontSize: 15,
  },
  featuredName: {
    fontFamily: 'Manrope-SemiBold',
    color: '#fff',
    fontSize: 18,
  },
};

const SubBreedStyle = {
  container: {
    flex: 1,
  },
  buttonArea: {
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    height: 70,
    justifyContent: 'center',
  },
  button: {
    height: 40,
    width: '90%',
    backgroundColor: '#14B219',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
  },
  breedArea: {
    flexDirection: 'column',
  },
  breedName: {
    marginTop: 10,
    height: 30,
    marginLeft: 10,
  },
  breedTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 18,
    color: '#1F5D44',
  },
  buttonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 15,
    color: '#fff',
  },
  breedButtonArea: {
    margin: 10,
    marginBottom: 20,
  },
  breedButton: {
    height: 40,
    width: 100,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#14B219',
  },
  breedButtonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 15,
    color: '#14B219',
  },
  generalTextStyle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    color: '#333',
  },
  titleText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#000',
  },
  chevronBack: {
    position: 'absolute',
    zIndex: 1,
    left: 30,
    width: 40,
    height: 40,
    top: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
};

const PetSearchStyle = {
  container: {
    flex: 1,
  },
  timeInfoAreaText: {
    fontFamily: 'Manrope-Bold',
    color: '#fff',
    fontSize: 16,
    marginLeft: 5,
  },
  timeInfoAreaDot: {
    borderRadius: 99,
    width: 15,
    height: 15,
    backgroundColor: '#14B219',
    borderWidth: 2,
    borderColor: '#fff',
  },
  timeInfoArea: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 10,
    left: 10,
  },
  filteringText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#555',
    marginLeft: 5,
  },
  filterModalApplyText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#fff',
  },
  filterModalApply: {
    width: '100%',
    height: 50,
    backgroundColor: '#14B219',
    justifyContent: 'center',
    alignItems: 'center',
  },
  breedModalRowText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    color: '#777',
  },
  breedModalInfoArea: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 80,
    width: 280,
  },
  breedModalImgArea: {
    width: 80,
    height: 80,
    backgroundColor: '#eee',
    borderRadius: 8,
  },
  breedModalRow: {
    width: '100%',
    height: 80,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  filterModalMoreText: {
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterModalBreedTextStyle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 15,
    marginRight: 20,
  },
  filterModalIconArea: {
    width: 25,
    height: 25,
    alignItems: 'center',
  },
  filterModalBreedRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    backgroundColor: '#eee',
    borderRadius: 5,
    marginBottom: 20,
    height: 30,
  },
  filterModalBreedsBox: {
    width: '100%',
    marginTop: 10,
  },
  filterModalTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#000',
    alignSelf: 'center',
  },
  sortModalClose: {
    position: 'absolute',
    right: 10,
    top: -20,
    borderRadius: 99,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  filterElements: {
    height: 35,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 0.8,
    borderColor: '#888',
    marginLeft: 5,
  },
  sortingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sortButton: {
    height: 30,
    width: 110,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTop: {
    backgroundColor: '#fff',
  },
  modalRecentText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#3C4048',
    marginHorizontal: 10,
  },
  modalRecentTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 15,
    color: '#000',
    marginHorizontal: 10,
    marginTop: 10,
  },
  modalScrollView: {
    height: 200,
    backgroundColor: 'red',
    marginBottom: 10,
    marginTop: 5,
  },
  modalHeader: {
    width: '100%',
    height: 50,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2.22,

    elevation: 3,
  },
  modalCloseButton: {
    borderRadius: 99,
    marginLeft: 10,
  },
  modalHeaderTitle: {
    marginLeft: 20,
    fontFamily: 'Manrope-Regular',
    fontSize: 18,
    color: '#888',
  },
  filterModalHeaderTitle: {
    marginLeft: 20,
    fontFamily: 'Manrope-Regular',
    fontSize: 18,
    color: '#777',
  },
  modalCategoriesCardArea: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  modalCategoriesCard: {
    width: 60,
    height: 60,
    backgroundColor: '#fff',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  modalCategories: {
    height: 80,
    marginVertical: 10,
    flexDirection: 'row',
  },
  modalPrivateText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 13,
    color: '#3C4048',
    marginLeft: 10,
  },
  top: {
    flex: 0.1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  card: {
    marginTop: 10,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 10,
  },
  imgArea: {
    width: '100%',
    height: '100%',
  },
  cardBottom: {
    backgroundColor: '#fff',
    width: '100%',
    height: 100,
    padding: 10,
    flexDirection: 'column',
    justifyContent: 'center',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  title: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#888',
  },
  cardBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardIconArea: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 50,
    justifyContent: 'space-between',
    marginTop: 5,
  },
  petInfoText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 13,
    color: '#666',
  },
  viewProfile: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
    color: '#14B219',
  },
  dot: {
    backgroundColor: '#888',
    borderRadius: 99,
    borderWidth: 1,
  },
  filterArea: {
    height: 50,
    paddingHorizontal: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchAreaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
  },
};

const CreateAdScreen1Style = {
  container: {
    flex: 1,
  },
  header: {
    flex: 0.1,
    backgroundColor: '#1F5D44',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    color: '#fff',
    fontSize: 20,
  },
  cardTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    alignSelf: 'center',
    color: '#1F5D44',
    marginBottom: 20,
  },
  chosenCategory: {
    fontFamily: 'Manrope-Bold',
    fontSize: 15,
    alignSelf: 'center',
    color: '#111',
    marginTop: 20,
  },
  tabStyle: {
    borderWidth: 0,
    borderColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  activeTabStyle: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#14B219',
  },
  tabTextStyle: {
    color: '#666',
  },
  activeTabTextStyle: {
    color: '#14B219',
  },
  categoryButton: {
    width: '100%',
    height: 40,
    alignItems: 'center',
    paddingLeft: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  categoryActiveButton: {
    width: '100%',
    height: 40,
    alignItems: 'center',
    borderBottomWidth: 0.7,
    borderColor: '#666',
    paddingLeft: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#14B219',
    borderRadius: 5,
  },
  categoryText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#222',
  },
  categoryActiveText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#fff',
  },
  nextButton: {
    width: '70%',
    height: 40,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#14B219',
    alignSelf: 'center',
    marginTop: 30,
  },
  nextButtonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#fff',
  },
};

const CreateAdScreen2Style = {
  container: {
    flex: 1,
  },
  header: {
    flex: 0.1,
    backgroundColor: '#1F5D44',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    color: '#fff',
    fontSize: 20,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputLabel: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#222',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  optionText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    alignSelf: 'center',
    marginLeft: 5,
  },
  infoText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 12,
    marginTop: 5,
    color: '#1F5D44',
  },
  infoTextGrey: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    marginTop: 5,
    color: '#444',
    marginLeft: 10,
  },
  inputAge: {
    height: 45,
    borderWidth: 0.8,
    borderRadius: 5,
    marginTop: 5,
    borderColor: '#555',
    padding: 10,
    width: 150,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputLocation: {
    height: 45,
    borderWidth: 0.8,
    borderRadius: 5,
    marginTop: 5,
    borderColor: '#555',
    padding: 10,
    width: 180,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputAgeText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#aaa',
  },
  ageModalClose: {
    position: 'absolute',
    right: 10,
    top: -20,
    borderRadius: 99,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  moneyTypeOptionsText: {
    fontFamily: 'Manrope-SemiBold',
    color: '#555',
    fontSize: 15,
    marginHorizontal: 5,
  },
  moneyTypeOptionsTitle: {
    fontFamily: 'Manrope-Bold',
    color: '#333',
    fontSize: 18,
  },
  nextButtonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#fff',
  },
  permissionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 30,
    marginTop: 20,
  },
  rulesTextArea: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  rulesTextBold: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
    color: '#222',
  },
  rulesText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
    color: '#666',
  },
  inputMoneyType: {
    height: 45,
    borderWidth: 0.8,
    borderRadius: 5,
    borderColor: '#555',
    padding: 10,
    width: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cameraArea: {
    width: 120,
    height: 120,
    backgroundColor: '#ddd',
    marginTop: 10,
    borderRadius: 5,
    borderWidth: 0.4,
    borderColor: '#555',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  selectedImagesArea: {
    width: 150,
    height: 150,
    backgroundColor: '#ddd',
    marginTop: 10,
    borderRadius: 5,
    borderWidth: 0.4,
    borderColor: '#555',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  imgArea: {
    width: 120,
    height: 120,
    backgroundColor: '#ddd',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginRight: 10,
    borderWidth: 5,
    borderColor: '#777',
  },
  imgDeleteButton: {
    backgroundColor: 'red',
    width: 25,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 99,
    position: 'absolute',
    top: -8,
    right: -5,
  },
};

const CreateAdScreen3Style = {
  container: {
    flex: 1,
  },
  header: {
    flex: 0.1,
    backgroundColor: '#1F5D44',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    color: '#fff',
    fontSize: 20,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: 'red',
    textAlign: 'center',
  },
  secondaryText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    color: '#222',
    textAlign: 'center',
  },
  line: {
    width: '28%',
    borderWidth: 0.4,
    backgroundColor: '#1F5D44',
  },
  lineTextArea: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 30,
    marginHorizontal: 10,
  },
  lineText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#1F5D44',
  },
  modalButton: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  modalButtonText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: 'blue',
  },
  tabStyle: {
    borderWidth: 0,
    borderColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  activeTabStyle: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#14B219',
  },
  tabTextStyle: {
    color: '#666',
  },
  activeTabTextStyle: {
    color: '#14B219',
  },
  buttonText: {
    fontFamily: 'Manrope-Bold',
    color: '#fff',
    fontSize: 14,
  },
  modalTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#555',
    marginBottom: 20,
  },
  modalCloseButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    right: 10,
  },
};

const CreateAdScreen4Style = {
  container: {
    flex: 1,
  },
  header: {
    flex: 0.1,
    backgroundColor: '#1F5D44',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    color: '#fff',
    fontSize: 20,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  body: {
    flex: 1,
    justifyContent: 'center',
  },
  card: {
    alignItems: 'center',
  },
  mainText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#111',
  },
  secondaryText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    color: '#333',
    marginTop: 10,
    textAlign: 'center',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 45,
    backgroundColor: '#14B219',
    borderRadius: 5,
    paddingHorizontal: 10,
    marginTop: 10,
  },
  buttonRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#fff',
    marginLeft: 10,
  },
};

const MessagesStyle = {
  container: {
    alignItems: 'center',
    flex: 1,
  },
  header: {
    backgroundColor: '#1F5D44',
    width: '100%',
    height: 70,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    flexDirection: 'row',
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#fff',
  },
  headerText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 20,
    color: '#fff',
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: 'purple',
  },
  adName: {
    fontFamily: 'Manrope-Bold',
    fontSize: 15,
    color: '#111',
  },
  read: {
    position: 'absolute',
    bottom: 5,
    right: 10,
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    color: '#14B219',
  },
  unread: {
    position: 'absolute',
    bottom: 5,
    right: 10,
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    color: 'red',
  },
  messageDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  personName: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    marginLeft: 10,
  },
  date: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    color: '#666',
    marginTop: 5,
  },
};

const MessagesDetailStyle = {
  container: {
    alignItems: 'center',
    flex: 1,
  },
  modalRulesText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    color: '#222',
    marginTop: 20,
  },
  body: {
    flex: 1,
  },
  modalClose: {
    position: 'absolute',
    right: 10,
    top: -5,
  },
  modalText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 17,
  },
  modalContainer: {
    flex: 1,
    marginVertical: 20,
  },
  header: {
    backgroundColor: '#1F5D44',
    width: '100%',
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  personName: {
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
    color: '#fff',
  },
  phoneNumber: {
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
    color: '#14B219',
  },
  cardImg: {
    width: 80,
    height: 80,
    marginLeft: 10,
    borderRadius: 8,
  },
  cardTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#1F5D44',
  },
  cardTextAreaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  date: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    color: '#444',
  },
  type: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 12,
    color: '#14B219',
    marginLeft: 10,
  },
  messageBox: {
    backgroundColor: '#CDE990',
    alignSelf: 'flex-end',
    padding: 10,
    borderRadius: 5,
    margin: 10,
    flexDirection: 'column',
    justifyContent: 'space-between',
    maxWidth: '80%',
  },
  termsText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    color: '#888',
  },
  messageReceive: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    marginBottom: 5,
  },
  messageSend: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    marginBottom: 5,
  },
};

const BreedDetailStyle = {
  titleText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#000',
  },
  generalInfoText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
    color: '#000',
  },
  generalTextStyle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    color: '#333',
  },
  sectionTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 22,
    alignSelf: 'center',
    marginBottom: 15,
  },
  largeImg: {
    width: null,
    height: null,
    flex: 1,
    resizeMode: 'contain',
  },
  seperator: {
    width: '92%',
    height: 50,
    marginTop: 10,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  line: {
    width: '100%',
    borderWidth: 0.7,
    borderColor: '#ddd',
  },
  seperatorIcon: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 99,
    width: 50,
    height: 50,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    left: 160,
  },
  infoBarRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  infoBarText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
  },
  generalInfoTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 15,
    color: '#1F5D44',
  },
  generalInfoColumn: {
    flexDirection: 'column',
    width: '50%',
    height: '100%',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  buttonArea: {
    width: '100%',
    height: 70,
    backgroundColor: '#1F5D44',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
  },
  button: {
    width: '90%',
    height: 40,
    borderRadius: 30,
    backgroundColor: '#14B219',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#fff',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  infoTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#000',
  },
  petInfo: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    color: '#666',
  },
  adDate: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    color: '#999',
    marginLeft: 5,
  },
  heartButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 99,
    position: 'absolute',
    top: 370,
    left: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  callButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 99,
    position: 'absolute',
    top: 370,
    right: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  messageButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 99,
    position: 'absolute',
    top: 370,
    right: 70,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  emptyButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 99,
    position: 'absolute',
    top: 370,
    right: 120,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  categoryTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#000',
  },
  fieldTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 13,
    color: '#000',
  },
  greyLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#ddd',
    marginTop: 5,
  },
  avatar: {
    width: 45,
    height: 45,
    backgroundColor: 'red',
    borderRadius: 99,
    position: 'absolute',
    top: -22.5,
    left: 'auto',
  },
  avatarName: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#000',
    marginTop: 30,
  },
  filledButton: {
    height: 40,
    width: '42%',
    backgroundColor: '#14B219',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  outlineButton: {
    height: 40,
    width: '90%',
    borderWidth: 1,
    borderColor: '#14B219',
    borderRadius: 30,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dotStyle: {
    position: 'absolute',
    zIndex: 1,
    right: 20,
    width: 40,
    height: 40,
    top: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chevronBack: {
    position: 'absolute',
    zIndex: 1,
    left: 30,
    width: 40,
    height: 40,
    top: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowCenter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fieldArea: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  iconArea: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fieldText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
    color: '#666',
  },
  tabStyle: {
    borderWidth: 0,
    borderColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  activeTabStyle: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#14B219',
  },
  tabTextStyle: {
    color: '#666',
  },
  activeTabTextStyle: {
    color: '#14B219',
  },
  explanation: {
    padding: 20,
  },
  explanationPhragraph: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#666',
    lineHeight: 25,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  modalTitle: {
    width: '100%',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBody: {
    width: '100%',
    height: 150,
  },
  modalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: 55,
  },
  closeModal: {
    width: 40,
    height: 40,
    borderRadius: 99,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    right: 10,
    top: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,

    elevation: 6,
    zIndex: 1,
  },
};

const ProfileStyle = {
  container: {
    flex: 1,
  },
  ownerModaInputTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#222',
    textAlign: 'center',
    alignSelf: 'center',
  },
  header: {
    flex: 0.1,
    backgroundColor: '#1F5D44',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 50,
    width: '100%',
    borderTopWidth: 0.8,
    borderColor: '#888',
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#fff',
  },
  body: {
    flex: 1,
    alignItems: 'center',
  },
  avatar: {
    height: 150,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarImg: {
    width: 80,
    height: 80,
    borderRadius: 99,
    backgroundColor: 'purple',
  },
  avatarText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 18,
    color: '#555',
    marginTop: 10,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 50,
    width: '90%',
    borderTopWidth: 0.8,
    borderColor: '#888',
  },
  leftRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileRowText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#555',
    marginLeft: 10,
  },
};

const SettingsStyle = {
  container: {
    flex: 1,
  },
  header: {
    backgroundColor: '#1F5D44',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 0.2,
  },
  headerTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    color: '#fff',
  },
  settingsTitle: {
    width: '100%',
    height: 40,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  settingsTitleText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 16,
    color: '#555',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 50,
    width: '100%',
    borderTopWidth: 0.8,
    borderColor: '#888',
  },
  settingsRowText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#555',
    marginLeft: 10,
  },
  leftRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
};

export {
  AccountInfoStyles,
  OwnerInfoStyles,
  HomeStyle,
  MyAddsStyles,
  DetailStyle,
  BreedsStyle,
  SubBreedStyle,
  PetSearchStyle,
  CreateAdScreen1Style,
  CreateAdScreen2Style,
  CreateAdScreen3Style,
  CreateAdScreen4Style,
  MessagesStyle,
  MessagesDetailStyle,
  BreedDetailStyle,
  ProfileStyle,
  SettingsStyle,
};
